### ISSUE TITLE
Add new artifacts to tenant deployment

### ISSUE THREAD

**Issue by tomeszmh** [aws-samples/aws-saas-factory-ref-solution-serverless-saas#17]
Can you provide some details or example how can I add a tenant related stack written in CDK python? If a new tenant registers we need another two apps to run at every tenant. 
As i assume we should create all of our resources with tenant id prefixes because of tenant isolation.
Also CDK doesn't create standalone CFN templates, so I assume it doesn't fit to the process handled by lambda-deploy-tenant-stack.py lambda handler.

**Comment by anubhavynr** [comment]
Hi @tomeszmh : 
You would use cdk deploy with parameters in this case.
https://docs.aws.amazon.com/cdk/v2/guide/parameters.html

Further, I would recommend that you look at this blog post: 
https://aws.amazon.com/blogs/devops/parallel-and-dynamic-saas-deployments-with-cdk-pipelines/

This blog post extends the idea presented in this reference solution and uses CDK based approach. The concept still remains the same, where you uses DynamoDB to keep track of tenant installations.

**Comment by attainmax** [comment]
Hi Anubhav, 

Thanks for the reference architecture. Its really great to get an comprehensive insight into serverless saas.

I am running lab 5 on Cloud9 and noticed that the CodeCommit repository for Code pipeline serverless-saas-pipeline is not being created. (Although the documentation indicates that The pipeline has already been created as part of the initialization script you ran at the start of this lab.)

Due to this subsequent steps are failing. 

Is there a way to add the serverless-saas-pipeline seperately to codecommit  ?


<img width="625" alt="errorPipeline" src="https://user-images.githubusercontent.com/100391611/155638824-14a15b40-8fd8-416d-92db-55a636b5586b.PNG">
<img width="466" alt="Error" src="https://user-images.githubusercontent.com/100391611/155638827-9a824253-801f-483b-82a8-db8555f03a32.PNG">
<img width="656" alt="commit" src="https://user-images.githubusercontent.com/100391611/155639045-3c93467b-eeba-4c34-8b1a-69d124d961a2.PNG">

**Comment by anubhavynr** [comment]
Hi @attainmax - you can look at this code to see how this is created:

https://github.com/aws-samples/aws-serverless-saas-workshop/blob/main/Lab5/scripts/deployment.sh#L25
