### ISSUE TITLE
User signup for different tenants

### ISSUE THREAD

**Issue by omarghatrify** [aws-samples/aws-saas-factory-ref-solution-serverless-saas#49]
I was wondering how a user will be able to sign up using email for multiple pooled tenants sharing the same cognito pool without getting an error that the email was already used while.

**Comment by anubhavynr** [comment]
This reference solution doesn't support one user to multiple tenant mapping. In that case you need a user registration that is agnostic of tenant so that you can register once with your email and then users can choose which all tenant they want to onboard too. The user sign-in process will probably need to ask which tenant user want to login with, vs starting from tenant and then ask for credentials.

The other alternative as you can guess is to leverage user pool per tenant.

**Comment by ujwalbukka** [comment]
Closing the issue. Please feel free to re-open it if you have questions
